### ISSUE TITLE
some building issue

### ISSUE THREAD

**Issue by cainbit** [kexecboot/kexecboot#13]
config the makefile with:
./autogen.sh --enable-static-linking --host=armv-unknown-linux-gnueabi --prefix=$HOME/dev

but the CFLAGS in "src/Makefile" is always "-g -O2", it seems the "--enable-static-linking" option doesn't work.

**Comment by jay7x** [comment]
Sorry, had no chance to build it to check.
@andrea-adami do you still have build setup?

If you can PR the fix we'd like to merge it!

**Comment by andrea-adami** [comment]
hi,
sorry for the delay but I really had no time.
I am building the OE toolchain tonight, I hope to test this weekend.
However I normally build with klcc thus the binaries are always static...

I remember to have seen an oddity last time, iirc the debug option was not considered.
I plan to test with musl libc, crosscompiling with openembedded.

How are you compiling it? Natively?
Cheers

**Comment by andrea-adami** [comment]
Hi,
I think I have reproduced the issue, in the autoconfig we set

GCC_FLAGS="$GCC_FLAGS -static"
or
GCC_FLAGS="$GCC_FLAGS -DDEBUG -O0 -g"

and in the top-Makefile.am we have
AM_CFLAGS = $(GCC_FLAGS)

I am re-reading  Automake manual, 27.6 Flag Variables Ordering ..
Hope to fixi it soon
Cheers.

**Comment by andrea-adami** [comment]
Well, yes, it seems trivial enough: please test on your side:

diff --git a/src/Makefile.am b/src/Makefile.am
index 6449c5a..c75df23 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -1,6 +1,6 @@
 bin_PROGRAMS=kexecboot
 
-kexecboot_CFLAGS = -I$(top_srcdir)
+kexecboot_CFLAGS = -I$(top_srcdir) $(AM_CFLAGS)
 
 kexecboot_SOURCES = \
        util.c \
