### ISSUE TITLE
Staying in "system" menu while timout is enabled with cause kexecboot gui to hang when the timer runs out

### ISSUE THREAD

**Issue by IMbackK** [kexecboot/kexecboot#17]

**Comment by jay7x** [comment]
I'm pretty sure we didn't tested this scenario as whole timeout-related part is very hack-ish.. Thank you for reporting! I'll have a look.

**Comment by IMbackK** [comment]
thanks, id like to ad that i am experiencing this on kexecboot 0.6 on a Motorola mapphone (xt875), on kernel 5.10

**Comment by jay7x** [comment]
JFYI I did testing environment setup and I guess I'm able to reproduce it now.. will dig deeper.

**Comment by jay7x** [comment]
One-line fix was merged to master!
Thank you for reporting!

**Comment by IMbackK** [comment]
thanks!
